# ─── EXAMPLE SHOWING ALL TASK FEATURES ─────────────────────────────────────────────────────────────────────
# setup:
#   desc: "⚙️ Setup environment: install dependencies, generate config"
# deps:
# - init:dev
#   prompt:
#     - "This will install tools and dependencies. Continue? (y/N)"
#   preconditions:
#     - sh: '[ -f ./configs/example.conf ]'
#       msg: "Missing configs/example.conf — please copy from example.conf"
#   cmds:
#     - echo "Installing dependencies..."
#     - echo "Generating configuration files..."
#   env:
#     SETUP_MODE: "auto"
#   vars:
#     # Override global PROJECT_NAME example
#     PROJECT_NAME: "{{.PROJECT_NAME}}"

# ─── Initialized Tasks ─────────────────────────────────
# init:dev:
#   desc: "Initialize local/dev environment specifics"
#   internal: true
#   cmds:
#     - echo "Running init:dev task for ENV={{.ENV}}"
#   platforms: [linux, darwin]  # Only run on macOS/Linux

# ─── Example Task with Inputs & Status Checks and directory ────────────────────────────────
# run-task:
#   desc: "Run a task with an input parameter"
#   dir: terraform/environments/dev
#   requires:
#     vars:
#       - task_name
#   cmds:
#     - echo "Running {{.task_name}}"
#   status:
#     - 'test -f output/{{.task_name}}.done'

# ──────────────────────────────────────────────────────────────────────────────
version: "3"

# ─── Global Configuration ───────────────────────────────────────────────────────
# Specify output style: options: [prefixed, unified]
output: prefixed

# Support .env files for environment variables
dotenv:
  - .env
  - .env.local

# Global environment variables (can be overridden per task)
env:
  ENV: '{{.ENV | default "dev"}}'
  DEBUG: '{{.DEBUG | default "false"}}'

# Global variables (static or dynamic via shell)
vars:
  # docker
  APP_DOCKER_IMAGE: sanjeevkt720/prometheus-demo:latest
  # kind
  KIND_CLUSTER_NAME: k8s-monitoring-control-plane
  DEV_CLUSTER: k8s-monitoring
  DEV_NS: k8s-monitoring-ns
  # grafana/loki
  GRAF_HELM_REPO_URL: https://grafana.github.io/helm-charts
  GRAF_CUSTOM_HELM_REPO_NAME: grafana
  LOKI_HELM_CHART_NAME: loki
  LOKI_CUSTOM_HELM_CHART_NAME: loki
  LOKI_FINAL_HELM_VALUES_FILE: k8s/values/loki-helm-values.yaml
  READ_LOKI_HELM_VALUES_FILE: k8s/read_values/loki-helm-values.yaml
  LOKI_HELM_CHART_VERSION: 6.41.1
  # prometheus
  PROM_HELM_REPO_URL: https://prometheus-community.github.io/helm-charts
  PROM_HELM_CHART_NAME: kube-prometheus-stack
  PROM_CUSTOM_HELM_REPO_NAME: prometheus-community
  PROM_CUSTOM_HELM_CHART_NAME: prometheus
  PROM_FINAL_HELM_VALUES_FILE: k8s/values/kube-prometheus-helm-values.yaml
  READ_PROM_HELM_VALUES_FILE: k8s/read_values/kube-prometheus-helm-values.yaml
  PROM_HELM_CHART_VERSION: 77.11.1
  # services
  PROM_SVC: svc/prometheus-kube-prometheus-prometheus
  GRAF_SVC: svc/prometheus-grafana
  APP_SVC: svc/prometheus-demo-app-svc
  ALERTM_SVC: svc/alertmanager-operated
  # ports
  PROM_PORT: 9090
  APP_PORT: 3000
  ALERTM_PORT: 9093
  GRAF_PORT: "3002:80"
  # info
  GRAF_URL: "Grafana → http://localhost:3002"
  PROM_URL: "Prometheus → http://localhost:9090"
  APP_URL: "Prometheus → http://localhost:3000"
  ALERTM_URL: "Alert Manager → http://localhost:9093"


includes:
  # Example include of shared tasks
  common:
    taskfile: ./Taskfile.gitflow.yaml
    flatten: true


# # # # # # # --------- # # # # # # # --------- # # # # # #
# --------------------- Common Tasks ---------------------
# # # # # # # --------- # # # # # # # --------- # # # # # #
tasks:
  default:
    desc: "📋 List all tasks"
    cmds:
      - task --list-all


  # ─── Setup Task ──────────────────────────────────────────────────────────────
  setup:
    desc: "⚙️ Setup environment: install dependencies, generate config etc."
    cmds:
      - task: create-cluster-dev
      # - task: kind-load-images TODO: fix (wrong cluster name i think)
      - task: helm-install-prom
      - task: helm-install-loki
      - task: deploy-app


  # ─── Development Task ────────────────────────────────────────────────────────
  dev:
    desc: "🏗️ Provision and start local development environment"
    cmds:
      - task: get-graf-passwd
      - task: port-fwd-graf

  create-cluster-dev:
    desc: "Create a Kind cluster if it doesn't already exist"
    cmds:
      - kind create cluster -n {{.DEV_CLUSTER}} --image kindest/node:v1.33.1 || echo "Cluster already exists"
      - kubectx kind-{{.DEV_CLUSTER}}
      - kubectl create namespace {{.DEV_NS}} || echo "namespace already exists"
      - kubens {{.DEV_NS}}


  # ─── Production Task ─────────────────────────────────────────────────────────
  prod:
    desc: "🚀 Provision and deploy to production"


  # # # # # # # ---------- # # # # # # # ---------- # # # # # # #
  # System Management
  # # # # # # # ---------- # # # # # # # ---------- # # # # # # #
  ports:
    desc: "📋 List ports in use"
    cmds:
      - ss -tunl


  # # # # # # # ---------- # # # # # # # ---------- # # # # # # #
  # Docs
  # # # # # # # ---------- # # # # # # # ---------- # # # # # # #
  docs:
    desc: "🌐 Serve docs locally -> http://127.0.0.1:8000/docs/"
    cmds:
      - poetry run mkdocs serve --clean


  # # # # # # # ---------- # # # # # # # ---------- # # # # # # #
  # Misc
  # # # # # # # ---------- # # # # # # # ---------- # # # # # # #
  info:
    desc: "🌐 URLs to visit"
    cmds:
      - echo "Prometheus -> {{.PROM_URL}}"
      - echo "Grafana -> {{.GRAF_URL}}"
      - echo "App -> {{.APP_URL}}"
      - echo "Alert Manager -> {{.ALERTM_URL}}"

  status:
    desc: "Check if everything is running"
    cmds:
      - kubectl get all -n {{.DEV_NS}}

  versions:
    desc: "List current deployed versions"
    cmds:
      - mike list


# ─── Helm ───────────────────────────────────────────────────────────
  helm-install-prom:
    desc: "⚙️ Install Prometheus Helm Chart"
    cmds:
      - helm repo add {{.PROM_CUSTOM_HELM_REPO_NAME}} {{.PROM_HELM_REPO_URL}}
      - helm repo update
      - kubens {{.DEV_NS}}
      - helm install {{.PROM_CUSTOM_HELM_CHART_NAME}} {{.PROM_CUSTOM_HELM_REPO_NAME}}/{{.PROM_HELM_CHART_NAME}} --version {{.PROM_HELM_CHART_VERSION}} -f {{.PROM_FINAL_HELM_VALUES_FILE}}
      - task: prom-helm-values

  helm-install-loki:
    desc: "⚙️ Install Grafana Helm Chart"
    cmds:
      - helm repo add {{.GRAF_CUSTOM_HELM_REPO_NAME}} {{.GRAF_HELM_REPO_URL}}
      - helm repo update
      - kubens {{.DEV_NS}}
      - helm install {{.LOKI_CUSTOM_HELM_CHART_NAME}} {{.GRAF_CUSTOM_HELM_REPO_NAME}}/{{.LOKI_HELM_CHART_NAME}} --version {{.LOKI_HELM_CHART_VERSION}} -f {{.LOKI_FINAL_HELM_VALUES_FILE}}
      - task: loki-helm-values

  helm-upgrade-all:
    desc: "⚙️ Upgrade Prometheus Helm Chart"
    cmds:
      - kubens {{.DEV_NS}}
      - helm upgrade {{.PROM_CUSTOM_HELM_CHART_NAME}} {{.PROM_CUSTOM_HELM_REPO_NAME}}/{{.PROM_HELM_CHART_NAME}} -f {{.PROM_FINAL_HELM_VALUES_FILE}}
      - helm upgrade {{.LOKI_CUSTOM_HELM_CHART_NAME}} {{.GRAF_CUSTOM_HELM_REPO_NAME}}/{{.LOKI_HELM_CHART_NAME}} -f {{.LOKI_FINAL_HELM_VALUES_FILE}}

  prom-helm-values:
    desc: "Save Prometheus Helm chart values"
    cmds:
      - helm show values {{.PROM_CUSTOM_HELM_REPO_NAME}}/{{.PROM_HELM_CHART_NAME}} --version {{.PROM_HELM_CHART_VERSION}} > {{.READ_PROM_HELM_VALUES_FILE}}
      - echo "Open {{.READ_PROM_HELM_VALUES_FILE}}"

  loki-helm-values:
    desc: "Save Grafana Helm chart values"
    cmds:
      - helm show values {{.GRAF_CUSTOM_HELM_REPO_NAME}}/{{.LOKI_HELM_CHART_NAME}} --version {{.LOKI_HELM_CHART_VERSION}} > {{.READ_LOKI_HELM_VALUES_FILE}}
      - echo "Open {{.READ_LOKI_HELM_VALUES_FILE}}"


# ─── kubectl ───────────────────────────────────────────────────────────
  get-graf-passwd:
    desc: "Print Grafana password"
    cmds:
      - kubectl --namespace {{.DEV_NS}} get secrets prometheus-grafana -o jsonpath="{.data.admin-password}" | base64 -d ; echo


# ─── App ───────────────────────────────────────────────────────────
  deploy-app:
    desc: "Deploy our application into the cluster"
    cmds:
      - kubens {{.DEV_NS}}
      - kubectl create -f k8s/
      - task: apply-app

  apply-app:
    desc: "Deploy our application into the cluster"
    cmds:
      - kubens {{.DEV_NS}}
      - kubectl apply -f k8s/


# ─── Port Forward ───────────────────────────────────────────────────────────
  port-fwd-prom:
    desc: "Port forward Prometheus"
    cmds:
      - kubens {{.DEV_NS}}
      - kubectl port-forward {{.PROM_SVC}} {{.PROM_PORT}}

  port-fwd-app:
    desc: "Port forward App"
    cmds:
      - kubens {{.DEV_NS}}
      - kubectl port-forward {{.APP_SVC}} {{.APP_PORT}}

  port-fwd-alertm:
    desc: "Port forward App"
    cmds:
      - kubens {{.DEV_NS}}
      - kubectl port-forward {{.ALERTM_SVC}} {{.ALERTM_PORT}}

  port-fwd-graf:
    desc: "Port forward Grafana"
    cmds:
      - kubens {{.DEV_NS}}
      - kubectl port-forward {{.GRAF_SVC}} {{.GRAF_PORT}}


# ─── kind ───────────────────────────────────────────────────────────
  kind-load-images:
    desc: "Load images into the cluster to spid up provisioning"
    cmds:
      - kubens {{.DEV_NS}} || echo "error switching k8s ns"
      - docker pull {{.APP_DOCKER_IMAGE}} || echo "error pulling images"
      - kind load docker-image {{.APP_DOCKER_IMAGE}} --name {{.KIND_CLUSTER_NAME}} || echo "error transferring images"


  # ─── Cleanup Tasks ───────────────────────────────────────────────────────────
  delete-app:
    desc: "Deploy our application into the cluster"
    cmds:
      - kubens {{.DEV_NS}}
      - kubectl delete -f k8s/

  cleanup-dev:
    desc: "🔁 Cleanup development resources only"
    cmds:
      # - kubens {{.DEV_NS}} || echo "NS switch failed - Error not found"
      # - helm uninstall {{.PROM_CUSTOM_HELM_CHART_NAME}} || echo "Helm uninstall failed - Error not found"
      # - kubectl delete -f k8s/ || echo "k8s/ deployment doesnt exist"
      # - docker stop {{.KIND_CLUSTER_NAME}} || echo "Container not running"
      # - helm repo remove {{.PROM_CUSTOM_HELM_REPO_NAME}} || echo "Remove Repo failed - Error not found"
      - kind delete cluster -n {{.DEV_CLUSTER}} || echo "Delete Cluster failed - Error not found"

  cleanup-prod:
    desc: "🔐 Cleanup production resources only"

  cleanup-all:
    desc: "🧼 Cleanup dev and prod in one swoop"


  # # # # # # # ---------- # # # # # # # ---------- # # # # # # #
  # FFMPEG Compression
  # # # # # # # ---------- # # # # # # # ---------- # # # # # # #
  mkdir-assets:
    desc: Create the assets/ directory if it doesn't exist
    cmds:
      - cmd: mkdir -p assets
        silent: true
        platforms: [linux, darwin]
      - cmd: powershell -NoProfile -Command "New-Item -ItemType Directory -Force assets | Out-Null"
        silent: true
        platforms: [windows]

  compress:
    desc: Compress a video to assets/demo-video-small.mp4 (pass video=....mp4)
    deps: [mkdir-assets]
    requires:
      vars: [video]
    vars:
      # Optional overrides at runtime: task compress video=... crf=30 preset=fast
      crf: "{{.crf | default 28}}"
      preset: '{{.preset | default "veryfast"}}'
    cmds:
      - >
        ffmpeg -i "{{.video}}"
        -vf "scale=1280:-2,fps=24"
        -c:v libx264 -crf {{.crf}} -preset {{.preset}}
        -movflags +faststart
        -c:a aac -b:a 96k
        assets/demo-video-small.mp4
        -y
    sources:
      - "{{.video}}"
    generates:
      - "assets/demo-video-small.mp4"

  compress-gif:
    desc: Compress a GIF to assets/demo-video-small.gif (pass gif=....gif)
    deps: [mkdir-assets]
    requires:
      vars: [gif]
    vars:
      fps: "{{.fps | default 8}}"
      colors: "{{.colors | default 64}}"
    cmds:
      # Step 1: Generate optimized palette
      - >
        ffmpeg -y -i "{{.gif}}"
        -vf "fps={{.fps}},scale=iw:-1:flags=lanczos,palettegen=max_colors={{.colors}}"
        assets/palette.png
      # Step 2: Apply palette
      - >
        ffmpeg -y -i "{{.gif}}" -i assets/palette.png
        -lavfi "fps={{.fps}},scale=iw:-1:flags=lanczos[x];[x][1:v]paletteuse=dither=bayer:bayer_scale=5"
        assets/demo-video-small.gif
      - rm -f assets/palette.png
    sources:
      - "{{.gif}}"
    generates:
      - "assets/demo-video-small.gif"
