apiVersion: apps/v1

kind: Deployment

metadata:
  name: prometheus-demo-app
  labels:
    app: prometheus-demo-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: prometheus-demo-app

  template:
    metadata:
      labels:
        app: prometheus-demo-app
    spec:
      containers:
      - image: sanjeevkt720/prometheus-demo:latest
        name: prometheus-demo-app
        ports:
          - containerPort: 3000
