apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-secret
  namespace: k8s-monitoring-ns
type: Opaque
stringData:
  webhook-url: "REMOVED<==services/T096B2LBJKY/B09J0BK67MW/wafPqY7CV5c4OHHjZWfPKn2L"